[versions]
accompanistPermissions = "0.37.3"
activity = "1.13.0"
adaptiveLayout = "1.3.0"
adaptiveNavigation = "1.3.0"
adaptiveVersion = "1.3.0"
androidxMaterial = "1.12.0"
annotation = "1.10.0"
appauth = "0.11.1"
appcompat = "1.8.0"
baselibrary = "3.2.0-alpha11"
biometric = "1.1.0"
browser = "1.10.0"
ccp = "2.7.3"
circleimageview = "3.1.0"
coilNetworkOkhttp = "3.6.0"
coilCompose = "3.6.0"
compose = "1.0.0-beta10"
composeBom = "2026.08.00"
constraintlayout = "2.2.2"
converterGson = "3.0.0"
converterScalars = "3.0.0"
countryPicker = "2.1.0"
datastorePreferences = "1.2.1"
desugar_jdk_libs = "2.1.5"
dots = "1.0.1"
espressoCore = "3.7.0"
fragment = "1.9.0"
fuelVersion = "2.3.1"
glide = "5.0.9"
googleMaterial = "1.14.0"
grpcOkhttp = "1.83.1"
grpcProtobufLite = "1.83.1"
grpcStub = "1.83.1"
hiltAndroid = "2.60.1"
hiltCompiler = "2.60.1"
javaxAnnotationApi = "1.3.2"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlin = "2.4.10"
kotlinxCoroutinesTest = "1.11.0"
kotlinxSerializationJson = "1.11.0"
leanback = "1.2.0"
lib_image_androidVersion = "bf90c6cb90"
lib_signal_double_ratchet_java = "c4a12f8fcd"
lib_smsmms_android = "6e3ec28642"
lifecycleExtensions = "2.2.0"
lifecycleViewmodelCompose = "2.11.0"
lifecycleViewmodelKtx = "2.11.0"
material = "1.14.0"
material3 = "1.4.0"
materialIconsCore = "1.7.8"
materialIconsExtended = "1.7.8"
materialVersion = "1.12.0"
navigationCompose = "2.10.0"
okhttp = "2.7.5"
okhttpBom = "5.5.0"
pagingCompose = "3.5.1"
pagingGuava = "3.5.1"
pagingRuntime = "3.5.1"
pagingRxjava2 = "3.5.1"
pagingRxjava3 = "3.5.1"
preferenceKtx = "1.2.1"
protobufKotlinLite = "4.36.0"
retrofit = "3.0.0"
roomKtx = "2.8.4"
roomRuntime = "2.8.4"
securityCrypto = "1.1.0"
startupRuntime = "1.2.0"
swiperefreshlayout = "1.2.0"
uiTestJunit4 = "1.12.0"
volley = "1.2.1"
widgetAndroid = "17ed994b6c"
workRuntime = "2.11.2"
uiTextGoogleFonts = "1.12.0"
pagingCommon = "3.5.1"
datastorePreferencesCore = "1.2.1"
foundationLayout = "1.12.0"
documentfile = "1.1.0"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidx-adaptive-layout = { module = "androidx.compose.material3.adaptive:adaptive-layout", version.ref = "adaptiveLayout" }
androidx-adaptive-navigation = { module = "androidx.compose.material3.adaptive:adaptive-navigation", version.ref = "adaptiveNavigation" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-baselibrary = { module = "androidx.databinding:baseLibrary", version.ref = "baselibrary" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "materialIconsCore" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-compose-material-material = { module = "androidx.compose.material:material" }
androidx-compose-material3-adaptive-adaptive = { module = "androidx.compose.material3.adaptive:adaptive", version.ref = "adaptiveVersion" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-leanback = { module = "androidx.leanback:leanback", version.ref = "leanback" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "materialVersion" }
androidx-material-v178 = { module = "androidx.compose.material:material", version.ref = "androidxMaterial" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }
androidx-paging-guava = { module = "androidx.paging:paging-guava", version.ref = "pagingGuava" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "pagingRuntime" }
androidx-paging-rxjava2 = { module = "androidx.paging:paging-rxjava2", version.ref = "pagingRxjava2" }
androidx-paging-rxjava3 = { module = "androidx.paging:paging-rxjava3", version.ref = "pagingRxjava3" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "preferenceKtx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
androidx-runtime-rxjava2 = { module = "androidx.compose.runtime:runtime-rxjava2" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startupRuntime" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }
appauth = { module = "net.openid:appauth", version.ref = "appauth" }
ccp = { module = "com.hbb20:ccp", version.ref = "ccp" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilNetworkOkhttp" }
compose = { module = "com.github.bumptech.glide:compose", version.ref = "compose" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "converterScalars" }
country-picker = { module = "com.github.arpitkatiyar1999:Country-Picker", version.ref = "countryPicker" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
dots = { module = "com.github.tizisdeepan:dots", version.ref = "dots" }
fuel = { module = "com.github.kittinunf.fuel:fuel", version.ref = "fuelVersion" }
fuel-android = { module = "com.github.kittinunf.fuel:fuel-android", version.ref = "fuelVersion" }
fuel-coroutines = { module = "com.github.kittinunf.fuel:fuel-coroutines", version.ref = "fuelVersion" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
grpc-okhttp = { module = "io.grpc:grpc-okhttp", version.ref = "grpcOkhttp" }
grpc-protobuf-lite = { module = "io.grpc:grpc-protobuf-lite", version.ref = "grpcProtobufLite" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpcStub" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltCompiler" }
javax-annotation-api = { module = "javax.annotation:javax.annotation-api", version.ref = "javaxAnnotationApi" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
lib_signal_double_ratchet_java = { module = "com.github.smswithoutborders:lib_signal_double_ratchet_java", version.ref = "lib_signal_double_ratchet_java" }
lib_smsmms_android = { module = "com.github.smswithoutborders:lib_smsmms_android", version.ref = "lib_smsmms_android" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material-v180alpha01 = { module = "com.google.android.material:material", version.ref = "googleMaterial" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
okhttp = { module = "com.squareup.okhttp:okhttp", version.ref = "okhttp" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttpBom" }
okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp" }
protobuf-kotlin-lite = { module = "com.google.protobuf:protobuf-kotlin-lite", version.ref = "protobufKotlinLite" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
smswithoutborders-lib_image_android = { module = "com.github.smswithoutborders:lib_image_android", version.ref = "lib_image_androidVersion" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "uiTestJunit4" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }
androidx-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }
androidx-paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "pagingCommon" }
androidx-datastore-preferences-core = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "datastorePreferencesCore" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayout" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }
widget-android = { module = "com.github.shortmesh:Widget-android", version.ref = "widgetAndroid" }

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
